Preload data
jasp-stats/jaspCircular pull request #61
Opened 2024-10-17 17:12 UTC by Kucharssim

2025-01-31 11:48 UTC, Kucharssim commented
@vandenman Does this generally look how preload data should be done? thanks

2025-02-04 09:17 UTC, vandenman requested changes

2025-02-04 09:17 UTC, vandenman commented on inst/Description.qml
> +	title		: qsTr("Circular Statistics (update)")
why this change?

2025-02-04 09:18 UTC, vandenman commented
Looks good in general, just this one question about the title change.

2025-02-04 10:53 UTC, Kucharssim commented on inst/Description.qml
> +	title		: qsTr("Circular Statistics (update)")
Opps, that shouldn't be there. Thanks for spotting it

2025-02-04 12:29 UTC, merged